### ISSUE TITLE
Highlight or enclose strong collocations or idioms in quotes. in the article.

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/prompts#10]
It would be better for foreign language learner if the extension can highlight or enclose strong collocations or idioms in quotes.
For example:

Various members of the **(international community)** have condemned the incident, described by the Palestinian United Nations Ambassador as "an **(outrageous massacre)** ." **(United Nations Secretary-General)** António Guterres said " **(desperate civilians)** in Gaza need **(urgent help)** , including those in the **(besieged north)** where the United Nations has not been able to **(deliver aid)** in more than a week ," according to his spokesperson Stéphane Dujarric. Colombia announced it would suspend the purchase of weapons from Israel after the bloody incident, with Colombian President Gustavo Petro posting, "This is called genocide and is reminiscent of the Holocaust even if the world powers do not like to recognize it."

**Comment by theowenyoung** [comment]
Hi, Thanks for your feed, but this is not the main purpose of our plugin and we probably won't add this feature.
