### ISSUE TITLE
Translated sentence first, original sentence second.

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/prompts#5]
it would be better for foreign language learner if it is supported this mode, especially TTS(text to speech) with AI multilingual voices for bilingual text.
Example:
I love you. -> ( Anh yêu em. I love you.) instead (I love you. Anh yêu em.)

**Comment by theowenyoung** [comment]
Thank you for your suggestion, we are currently unable to implement this mode technically, and the current form is the only bilingual comparison mode we can achieve

**Comment by theowenyoung** [comment]
Hello, now you can enable this mode in Immersive Translate by opening [Settings] -> [Advanced Settings] -> [Translation first, original text follows], That's it.
