### ISSUE TITLE
separate sentences to chunking and comment translated.

### ISSUE THREAD

**Issue by trionline1234** [immersive-translate/prompts#9]
您希望的更新和改进是什么 | Update or Improve
For example:

𝐓𝐡𝐞 𝐩𝐨𝐰𝐞𝐫 𝐨𝐟 𝐠𝐫𝐚𝐭𝐢𝐭𝐮𝐝𝐞 𝐢𝐬 𝐚 𝐦𝐢𝐫𝐚𝐜𝐮𝐥𝐨𝐮𝐬 𝐟𝐨𝐫𝐜𝐞 . 𝐈𝐭 𝐜𝐚𝐧 𝐭𝐫𝐚𝐧𝐬𝐟𝐨𝐫𝐦 𝐲𝐨𝐮𝐫 𝐥𝐢𝐟𝐞 𝐢𝐧 𝐰𝐚𝐲𝐬 𝐲𝐨𝐮 𝐧𝐞𝐯𝐞𝐫 𝐭𝐡𝐨𝐮𝐠𝐡𝐭 𝐩𝐨𝐬𝐬𝐢𝐛𝐥𝐞
Convert to format:
(Sức mạnh của lòng biết ơn) 𝐓𝐡𝐞 𝐩𝐨𝐰𝐞𝐫 𝐨𝐟 𝐠𝐫𝐚𝐭𝐢𝐭𝐮𝐝𝐞 (là một lực lượng kỳ diệu) 𝐢𝐬 𝐚 𝐦𝐢𝐫𝐚𝐜𝐮𝐥𝐨𝐮𝐬 𝐟𝐨𝐫𝐜𝐞 . (Nó có thể biến đổi)𝐈𝐭 𝐜𝐚𝐧 𝐭𝐫𝐚𝐧𝐬𝐟𝐨𝐫𝐦 (cuộc sống của bạn) 𝐲𝐨𝐮𝐫 𝐥𝐢𝐟𝐞 (theo những cách mà bạn không bao giờ nghĩ đến) 𝐢𝐧 𝐰𝐚𝐲𝐬 𝐲𝐨𝐮 𝐧𝐞𝐯𝐞𝐫 𝐭𝐡𝐨𝐮𝐠𝐡𝐭 𝐩𝐨𝐬𝐬𝐢𝐛𝐥𝐞.

It will better for foreign language learner when text to speech with bilingual sentences.

**Comment by TaoLoading** [comment]
This is a good idea, we can use the sentence splitting ability of AI to achieve it. Later, I will launch this AI expert, but considering most users, the language of the translation may be different. Of course, you can also implement similar functionality based on the current prompt words. Thank you for your suggestion.

**Comment by TaoLoading** [comment]
Hello, the word-by-Word translation assistanthas been launched, currently translating into Chinese, you can modify it to translate into the language you need
